---

- name: 'Test playbook to write content into a file'
  hosts: all
  become: true
  gather_facts: false
  vars:
    content: 'Test_Content_Line'
    filepath: '/demo/hello.txt'
  tasks:
    - name: Create /demo directory
      ansible.builtin.file:
        path: /demo
        state: directory
        mode: '0755'
    - name: "Write content into a file"
      copy:
        dest: "{{ filepath }}"
        content: "{{ content }}"

    - name: "Check file {{ filepath }} stat result"
      stat:
        path: "{{ filepath }}"
      register: st

    - name: "Check if file {{ filepath }} exists"
      fail:
        msg: "{{ filepath }} doesnt exist"
      when: not st.stat.exists | bool

    - name: "Get {{ filepath }} content"
      command: "cat {{ filepath }}"
      register: cnt

    - name: "Check if {{ filepath }} content is correct"
      fail:
        msg: "{{ filepath }} doesnt have the correct content"
      when: '"{{ content }}" not in cnt.stdout'
